services:
    Tecnocreaciones\Bundle\ToolsBundle\Service\TimeAgoService:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\TimeAgoService
        arguments:
            - '@translator'
    tecno.service.time_ago:
        alias: 'Tecnocreaciones\Bundle\ToolsBundle\Service\TimeAgoService'
        public: true
    tecno.service.fixtures_dumper:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\FixturesDumperService
        calls:
            - [ setContainer, ['@service_container']]
    Tecnocreaciones\Bundle\ToolsBundle\Service\ImageManager:
        autowire: true
        arguments:
            - { "public_dir": "%kernel.project_dir%/../public" }
    Tecnocreaciones\Bundle\ToolsBundle\Controller\Select2EntityController:
        autowire: true
        tags: ['controller.service_arguments']