#parameters:
#    tecnoready.mailer_db.spool.class: Tecnoready\Common\Spool\ORM\DatabaseSpool
    
services:
    tecnoready.repository.email:
        class: Tecnoready\Common\Model\Email\ORM\EmailRepository
        factory: ['@doctrine.orm.default_entity_manager',getRepository]
        arguments: ['%tecnoready.mailer_db.spool.entity_class%']
    tecnoready.mailer_db.spool:
        class: "%tecnoready.mailer_db.spool.class%"
        arguments: ["@tecnoready.repository.email.em","%tecnoready.mailer_db.spool.entity_class%","%kernel.environment%","%tecnoready.mailer_db.spool.keep_sent_messages%"]
    mailer.spool.db:
        alias: tecnoready.mailer_db.spool
    mailer.mailer.default.spool.db:
        alias: tecnoready.mailer_db.spool
    tecnoready.mailer.adapter.orm:
        class: Tecnoready\Common\Service\Email\Adapter\DoctrineORMAdapter
        arguments: ["@doctrine","@tecnoready.repository.email.em",{ "email_queue_class" : "%tecnoready.mailer_db.spool.email_queue_class%", "email_template_class": "%tecnoready.mailer_db.spool.email_template_class%", "email_component_class": "%tecnoready.mailer_db.email_component_class%" }]
    Tecnoready\Common\Service\Email\TwigSwiftMailer:
        public: false
        arguments: ["@mailer","@twig","@tecnoready.mailer.adapter.orm",{ env: "%kernel.environment%", debug: "%kernel.debug%" }]
        calls:
            - [ setContainer, ["@service_container"]  ]
    tecnoready.swiftmailer:
        alias: Tecnoready\Common\Service\Email\TwigSwiftMailer
        public: true

    Tecnoready\Common\Service\Email\TwigSymfonyMailer:
        public: false
        arguments: ["@mailer","@twig","@tecnoready.mailer.adapter.orm","%tecnoready.mailer_db.spool.options%"]
        calls:
            - [ setContainer, ["@service_container"]  ]
    tecnoready.symfonymailer:
        alias: Tecnoready\Common\Service\Email\TwigSymfonyMailer
        public: true