#parameters:
#    tecnoready.swiftmailer_db.spool.class: Tecnoready\Common\Spool\ORM\DatabaseSpool
    
services:
    tecnoready.repository.email:
        class: Tecnoready\Common\Model\Email\ORM\EmailRepository
        factory: ['@doctrine.orm.default_entity_manager',getRepository]
        arguments: ['%tecnoready.swiftmailer_db.spool.entity_class%']
    tecnoready.swiftmailer_db.spool:
        class: "%tecnoready.swiftmailer_db.spool.class%"
        arguments: ["@tecnoready.repository.email.em","%tecnoready.swiftmailer_db.spool.entity_class%","%kernel.environment%","%tecnoready.swiftmailer_db.spool.keep_sent_messages%"]
    swiftmailer.spool.db:
        alias: tecnoready.swiftmailer_db.spool
    swiftmailer.mailer.default.spool.db:
        alias: tecnoready.swiftmailer_db.spool
    tecnoready.swiftmailer.adapter.orm:
        class: Tecnoready\Common\Service\Email\Adapter\DoctrineORMAdapter
        arguments: ["@doctrine","@tecnoready.repository.email.em",{ "email_queue_class" : "%tecnoready.swiftmailer_db.spool.email_queue_class%", "email_template_class": "%tecnoready.swiftmailer_db.spool.email_template_class%", "email_component_class": "%tecnoready.swiftmailer_db.email_component_class%" }]
    Tecnoready\Common\Service\Email\TwigSwiftMailer:
        public: false
        arguments: ["@mailer","@twig","@tecnoready.swiftmailer.adapter.orm",{ debug_mail: "%debug_mail%", env: "%kernel.environment%",from_email: "%mailer_user%", from_name: "%from_name%",debug: "%kernel.debug%" }]
        calls:
            - [ setContainer, ["@service_container"]  ]
    tecnoready.swiftmailer:
        alias: Tecnoready\Common\Service\Email\TwigSwiftMailer
        public: true