services:
    app.service.exporter.adapter:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\Exporter\Adapter\Doctrine2Adapter
        public: true
        calls:
            - [ setContainer, ['@service_container']  ]
    app.service.exporter:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\Exporter\ExporterManager
        public: true
        arguments: [{ env: '%kernel.environment%',documents_path: '%kernel.root_dir%/../var/documents',debug: '%kernel.debug%' } ]
        calls:
            - [ setContainer, ['@service_container']  ]
            - [ setAdapter, ["@app.service.exporter.adapter"]  ]