services:
    tecnocreaciones_tools.service.intro:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\Intro\IntroService
        calls:
            - [ setConfig, ["%tecnocreaciones_tools.intro.config%"]]
            - [ setTemplating, [@templating]]
            - [ setDoctrine, [@doctrine]]