services:
    tecnocreaciones_tools.service.intro:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\Intro\IntroService
        calls:
            - [ setAreas, ["%tecnocreaciones_tools.intro.areas%"]]