services:
    _defaults:
        public: '%services_defaults_public%'
    liform.transformer.compound:
        class: Tecnocreaciones\Bundle\ToolsBundle\Custom\Liform\Transformer\CompoundTransformer
        autowire: true
        arguments: ["@translator","@liform.guesser.validator","@liform.resolver"]
        tags:
            - { name: liform.transformer, form_type: compound}
    liform.transformer.choice:
        class: Tecnocreaciones\Bundle\ToolsBundle\Custom\Liform\Transformer\ChoiceTransformer
        autowire: true
        tags:
            - { name: liform.transformer, form_type: choice, widget: choice }
    liform.transformer.boolean:
        class: Tecnocreaciones\Bundle\ToolsBundle\Custom\Liform\Transformer\BooleanTransformer
        autowire: true
        tags:
            - { name: liform.transformer, form_type: checkbox, widget: checkbox }
    liform.transformer.array:
        class: Tecnocreaciones\Bundle\ToolsBundle\Custom\Liform\Transformer\CollectionTransformer
        arguments: ["@translator","@liform.guesser.validator","@liform.resolver"]
        tags:
            - { name: liform.transformer, form_type: collection, widget: collection }
    liform.transformer.button.submit:
        class: Tecnocreaciones\Bundle\ToolsBundle\Custom\Liform\Transformer\ButtonTransformer
        autowire: true
        tags:
            - { name: liform.transformer, form_type: submit, widget: submit }
            - { name: liform.transformer, form_type: button, widget: button }
    liform.transformer.string:
        class: Tecnocreaciones\Bundle\ToolsBundle\Custom\Liform\Transformer\StringTransformer
        autowire: true
        tags:
            - { name: liform.transformer, form_type: text, widget: text }
            - { name: liform.transformer, form_type: url, widget: url }
            - { name: liform.transformer, form_type: search, widget: search }
            - { name: liform.transformer, form_type: money, widget: money }
            - { name: liform.transformer, form_type: password, widget: password }
            - { name: liform.transformer, form_type: textarea, widget: textarea }
            - { name: liform.transformer, form_type: time, widget: time }
            - { name: liform.transformer, form_type: percent, widget: percent }
            - { name: liform.transformer, form_type: email, widget: email }
            - { name: liform.transformer, form_type: date, widget: date }
            - { name: liform.transformer, form_type: datetime, widget: datetime }
            - { name: liform.transformer, form_type: file, widget: file_widget }
            
    liform.transformer.readonly:
        class: Tecnocreaciones\Bundle\ToolsBundle\Custom\Liform\Transformer\ReadOnlyTransformer
        autowire: true
        tags:
            - { name: liform.transformer, form_type: readonly, widget: readonly }

    liform.transformer.hidden:
        class: Tecnocreaciones\Bundle\ToolsBundle\Custom\Liform\Transformer\HiddenTransformer
        autowire: true
        tags:
            - { name: liform.transformer, form_type: hidden, widget: hidden }

    liform.transformer.tetranz_select2entity:
        class: Tecnocreaciones\Bundle\ToolsBundle\Custom\Liform\Transformer\Select2EntityTransformer
        autowire: true
        tags:
            - { name: liform.transformer, form_type: tetranz_select2entity, widget: picker-select2 }

    Tecnocreaciones\Bundle\ToolsBundle\Service\DynamicViewManager\DynamicFormManager:
        autowire: true
    Tecnocreaciones\Bundle\ToolsBundle\Service\DynamicViewManager:
        autowire: true
    Tecnocreaciones\Bundle\ToolsBundle\Custom\Liform\SymfonyConstraintsParser:
        autowire: true