services:
    tecnocreaciones_tools.search.standard:
        class: Tecnocreaciones\Bundle\ToolsBundle\Model\Search\Filters\StandardFilters
    tecnocreaciones_tools.search:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\SearchService
        calls:
            - [ setFilterBlockRepository, [@app.repository.search.filter_block]]
            - [ setTwig, [@twig]]
            - [ addGroupFilter, [@tecnocreaciones_tools.search.standard]]
    tools.search.twig.extension:
        class: Tecnocreaciones\Bundle\ToolsBundle\Twig\Extension\SearchExtension
        tags:
            - { name: twig.extension }        
        calls:
            - [ setContainer, [@service_container]]
            - [ setSearchService, [@tecnocreaciones_tools.search]]
    app.repository.search.filter_block:
        class: Tecnocreaciones\Bundle\ToolsBundle\Model\Search\FilterBlockRepository
        tags:
            - { name: app.repository, class: %tecnocreaciones_tools.search.config.class.filter_block% }