services:
    Tecnocreaciones\Bundle\ToolsBundle\Service\TabsManager:
        autowire: true
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\TabsManager
        arguments: ["@request_stack","%tecnocreaciones_tools.service.tabs%"]
        calls:
            - [ setContainer, ['@service_container']  ]
    tecnoready.document_manager_disk_adapter:
        class: Tecnoready\Common\Service\ObjectManager\DocumentManager\Adapter\DiskAdapter
        arguments:
            - { "debug": "%kernel.debug%", "documents_path": "%kernel.root_dir%/../var/documents","env": "%kernel.environment%" }
    tecnoready.document_manager:
        class: Tecnoready\Common\Service\ObjectManager\DocumentManager\DocumentManager
    tecnoready.history_manager:
        class: Tecnoready\Common\Service\ObjectManager\HistoryManager\HistoryManager
    tecnoready.note_manager:
        class: Tecnoready\Common\Service\ObjectManager\NoteManager\NoteManager
    Tecnoready\Common\Service\ObjectManager\ObjectDataManager:
        public: true
        class: Tecnoready\Common\Service\ObjectManager\ObjectDataManager
        arguments: ["@tecnoready.document_manager","@tecnoready.history_manager","@tecnoready.note_manager","@app.service.exporter","@tecnocreaciones_tools.service.statistics_manager"]
    app.service.exporter.adapter:
        class: Tecnoready\Common\Service\ObjectManager\DocumentManager\ExporterManager\Adapter\DoctrineORMAdapter
        arguments: ["@doctrine.orm.default_entity_manager"]
    app.service.exporter:
        class: Tecnoready\Common\Service\ObjectManager\DocumentManager\ExporterManager\ExporterManager
        arguments: [ "@tecnoready.document_manager",{ "debug": '%kernel.debug%' } ]
        calls:
            - [ setAdapter, ["@app.service.exporter.adapter"]  ]