services:
    Tecnocreaciones\Bundle\ToolsBundle\Service\TabsManager:
        autowire: true
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\TabsManager
        arguments: ["@request_stack","%tecnocreaciones_tools.service.tabs%"]
        calls:
            - [ setContainer, ['@service_container']  ]
    tecnoready.document_manager_disk_adapter:
        class: Tecnoready\Common\Service\ObjectManager\DocumentManager\Adapter\DiskAdapter
        arguments:
            - { "debug": "%kernel.debug%", "documents_path": "%kernel.project_dir%/../var/documents","env": "%kernel.environment%" }
    tecnoready.document_manager:
        class: Tecnoready\Common\Service\ObjectManager\DocumentManager\DocumentManager
    Tecnoready\Common\Service\ObjectManager\HistoryManager\HistoryManager:
        class: Tecnoready\Common\Service\ObjectManager\HistoryManager\HistoryManager
    tecnoready.history_manager:
        alias: 'Tecnoready\Common\Service\ObjectManager\HistoryManager\HistoryManager'
        public: true
    tecnoready.note_manager:
        class: Tecnoready\Common\Service\ObjectManager\NoteManager\NoteManager
    Tecnoready\Common\Service\ObjectManager\ObjectDataManager:
        public: true
        class: Tecnoready\Common\Service\ObjectManager\ObjectDataManager
        arguments: ["@tecnoready.document_manager","@tecnoready.history_manager","@tecnoready.note_manager","@app.service.exporter","@tecnocreaciones_tools.service.statistics_manager"]
    app.service.exporter.adapter:
        class: Tecnoready\Common\Service\ObjectManager\DocumentManager\ExporterManager\Adapter\DoctrineORMAdapter
        arguments: ["@doctrine.orm.default_entity_manager"]
    app.service.exporter:
        class: Tecnoready\Common\Service\ObjectManager\DocumentManager\ExporterManager\ExporterManager
        arguments: [ "@tecnoready.document_manager",{ "debug": '%kernel.debug%' } ]
        calls:
            - [ setAdapter, ["@app.service.exporter.adapter"]  ]

#    Manejador de plantillas     
    Tecnoready\Common\Service\Template\Engine\PhpSpreadsheetXLSXEngine:
        arguments: []
        public: false
    Tecnoready\Common\Service\Template\Engine\TCPDFEngine:
        arguments: ["@twig"]
        public: false
    Tecnoready\Common\Service\Template\Engine\TCPDFNativeEngine:
        public: false
    Tecnoready\Common\Service\Template\Engine\TXTNativeEngine:
        public: false
    Tecnoready\Common\Service\Template\Engine\TXTEchoEngine:
        public: false
    Tecnoready\Common\Service\Template\Engine\WkhtmlToPDFEngine:
        arguments: ["@twig"]
        public: false
    Tecnoready\Common\Service\Template\TemplateService:
        arguments: [ {"debug":"%kernel.debug%", "env": "%kernel.environment%"} ]
        calls:
            - [ addEngine, ["@Tecnoready\\Common\\Service\\Template\\Engine\\TXTNativeEngine"]  ]
            - [ addEngine, ["@Tecnoready\\Common\\Service\\Template\\Engine\\TXTEchoEngine"]  ]
            - [ addEngine, ["@Tecnoready\\Common\\Service\\Template\\Engine\\TCPDFEngine"]  ]
            - [ addEngine, ["@Tecnoready\\Common\\Service\\Template\\Engine\\TCPDFNativeEngine"]  ]
            - [ addEngine, ["@Tecnoready\\Common\\Service\\Template\\Engine\\WkhtmlToPDFEngine"]  ]
            - [ addEngine, ["@Tecnoready\\Common\\Service\\Template\\Engine\\PhpSpreadsheetXLSXEngine"]  ]
#            - [ setAdapter, ["@app.service.exporter.adapter"]  ]