parameters:
    tecnocreaciones_tools.widget_block_grid.widget_block_grid_class: "Definir en configuracion"
    
services:
    Tecnoready\Common\Service\Block\WidgetManager:
        class: Tecnoready\Common\Service\Block\WidgetManager
        public: false
        autowire: true
        arguments:
            - "@tecno.widget.orm.adapter"
        
    tecnocreaciones_tools.service.grid_widget_box:
        public: true
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\GridWidgetBoxService
        calls:
            - [ setContainer, ['@service_container']]
    tecno.widget.orm.adapter:
        class: Tecnoready\Common\Model\Block\Adapter\WidgetORMAdapter
        arguments:
            - "%tecnocreaciones_tools.widget_block_grid.widget_block_grid_class%"
        calls:
            - [ setContainer, ['@service_container']]
    sonata.block.loader.service.widgets:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\Block\WidgetServiceLoader
        tags:
            - { name: sonata.block.loader }
    tecno.block.twig.extension:
        class: Tecnocreaciones\Bundle\ToolsBundle\Twig\Extension\BlockExtension
#        arguments: ['@code_mirror.asset_manager']
        autowire: true
        tags:
            - { name: twig.extension }
