parameters:
    tecnocreaciones_tools.widget_block_grid.widget_block_grid_class: "Definir en configuracion"
    
services:
    tecnocreaciones_tools.service.grid_widget_box:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\GridWidgetBoxService
        calls:
            - [ setContainer, ['@service_container']]
    tecnocreaciones_tools.service.orm.widget_box_manager:
        class: Tecnocreaciones\Bundle\ToolsBundle\Model\Block\Manager\BlockWidgetBoxManagerORM
        arguments:
            - "%tecnocreaciones_tools.widget_block_grid.widget_block_grid_class%"
        calls:
            - [ setContainer, ['@service_container']]
    block.main.summary:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\Block\Event\MainSummaryBlockEvent
        arguments:
            - "sonata.block.event.main.summary"
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.widgets, method: "onBlock" }
        calls:
            - [ setContainer, ['@service_container']]