parameters:
    tecnocreaciones_tools.widget_block_grid.widget_block_grid_class: "Definir en configuracion"
    
services:
    Tecnocreaciones\Bundle\ToolsBundle\Service\Block\BlockHelper:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\Block\BlockHelper
        public: false
        autowire: true
        
    tecnocreaciones_tools.service.grid_widget_box:
        public: true
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\GridWidgetBoxService
        calls:
            - [ setContainer, ['@service_container']]
    tecnocreaciones_tools.service.orm.widget_box_manager:
        class: Tecnocreaciones\Bundle\ToolsBundle\Model\Block\Manager\BlockWidgetBoxManagerORM
        arguments:
            - "%tecnocreaciones_tools.widget_block_grid.widget_block_grid_class%"
        calls:
            - [ setContainer, ['@service_container']]
    block.main.summary:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\Block\Event\MainSummaryBlockEvent
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.widgets, method: "onBlock" }
        calls:
            - [ setContainer, ['@service_container']]
    sonata.block.loader.service.widgets:
        class: Tecnocreaciones\Bundle\ToolsBundle\Service\Block\WidgetServiceLoader
        tags:
            - { name: sonata.block.loader }
    tecno.block.twig.extension:
        class: Tecnocreaciones\Bundle\ToolsBundle\Twig\Extension\BlockExtension
#        arguments: ['@code_mirror.asset_manager']
        autowire: true
        tags:
            - { name: twig.extension }
