block_widget_box_index:
    path: /{eventName}/
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:index
        _format: html
    requirements: { _method: GET }
    
block_widget_box_create:
    path: /{eventName}/create
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:create
        _format: html
    requirements: { _method: GET|POST }
    
block_widget_box_add_all:
    path: /{eventName}/add-all
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:addAll
        _format: html
    requirements: { _method: GET }
    
block_widget_box_delete_all:
    path: /{eventName}/delete-all
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:deleteAll
        _format: html
    requirements: { _method: GET }
    
block_widget_box_delete:
    path: /{id}/delete
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:delete
        _format: html
    requirements: { _method: GET }
    
block_widget_box_minimize:
    path: /{id}/minimize
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:minimize
        _format: html
    requirements: { _method: POST }
    
block_widget_box_maximize:
    path: /{id}/maximize
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:maximize
        _format: html
    requirements: { _method: GET }
    
block_widget_box_update:
    path: /update
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:update
        _format: html
    requirements: { _method: POST }
    
block_widget_box_refresh:
    path: /{id}/refresh
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:refresh
        _format: html
    requirements: { _method: GET }