block_widget_box_index:
    pattern: /
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:index
        _format: html
    requirements: { _method: GET }
    
block_widget_box_refresh:
    pattern: /{id}/refresh
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:refresh
        _format: html
    requirements: { _method: GET }
    
block_widget_box_create:
    pattern: /create
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:create
        _format: html
    requirements: { _method: GET|POST }
    
block_widget_box_add_all:
    pattern: /add-all
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:addAll
        _format: html
    requirements: { _method: GET }
    
block_widget_box_delete:
    pattern: /{id}/delete
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:delete
        _format: html
    requirements: { _method: GET }
    
block_widget_box_minimize:
    pattern: /{id}/minimize
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:minimize
        _format: html
    requirements: { _method: POST }
    
block_widget_box_maximize:
    pattern: /{id}/maximize
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:maximize
        _format: html
    requirements: { _method: GET }
    
block_widget_box_update:
    pattern: /update
    defaults:
        _controller:  TecnocreacionesToolsBundle:BlockWidgetBox:update
        _format: html
    requirements: { _method: POST }