#TecnocreacionesToolsTabs:
#    resource: "@TecnocreacionesToolsBundle/Resources/config/routing/tabs.yaml"
#    prefix: /tabs

tabs_save_current:
    path: /tabs/save-current.json
    defaults:
        _controller: tecnocreaciones.tools_bundle.controller_tools::tabSaveCurrentAction
        _format: json
    requirements: { _method: GET }
    
tabs_object_manager_documents_upload:
    path: /tabs/object-manager/documents/upload
    defaults:
        _controller:  tecnocreaciones.tools_bundle.controller_document_manager::uploadAction
        _format: html
    requirements: { _method: POST }
    
tabs_object_manager_documents_delete:
    path: /tabs/object-manager/documents/delete/{filename}
    defaults:
        _controller:  tecnocreaciones.tools_bundle.controller_document_manager::deleteAction
        _format: html
    requirements: { _method: GET }
    
tabs_object_manager_documents_get:
    path: /tabs/object-manager/documents/get/{filename}
    defaults:
        _controller:  tecnocreaciones.tools_bundle.controller_document_manager::getAction
        _format: html
    requirements: { _method: GET }
    
tabs_object_exporter_generate:
    path: /tabs/object-manager/exporter/generate
    defaults:
        _controller:  tecnocreaciones.tools_bundle.controller_exporter::generateAction
        _format: html
    requirements: { _method: POST }
    options:
        expose: true
    
tabs_object_exporter_get:
    path: /tabs/object-manager/exporter/get/{filename}
    defaults:
        _controller:  tecnocreaciones.tools_bundle.controller_exporter::getAction
        _format: html
    requirements: { _method: GET }
    
tabs_object_exporter_delete:
    path: /tabs/object-manager/exporter/delete/{filename}
    defaults:
        _controller:  tecnocreaciones.tools_bundle.controller_exporter::deleteAction
        _format: html
    requirements: { _method: GET }
    options:
        expose: true

tabs_object_exporter_download:
    path: /tabs/object-manager/exporter/download/{filename}
    defaults:
        _controller:  tecnocreaciones.tools_bundle.controller_exporter::downloadAction
        _format: html
    requirements: { _method: GET }
    options:
        expose: true

tabs_object_exporter_upload:
    path: /tabs/object-manager/exporter/upload
    defaults:
        _controller:  tecnocreaciones.tools_bundle.controller_exporter::uploadAction
        _format: html
    requirements: { _method: POST }
    options:
        expose: true

tabs_object_exporter_all:
    path: /tabs/object-manager/exporter/all
    defaults:
        _controller:  tecnocreaciones.tools_bundle.controller_exporter::allAction
        _format: html
    requirements: { _method: GET }
    options:
        expose: true
    
tabs_object_note_add:
    path: /tabs/object-manager/note/add
    defaults:
        _controller:  tecnocreaciones.tools_bundle.controller_note_manager::addAction
        _format: html
    requirements: { _method: POST }