#TecnocreacionesToolsTabs:
#    resource: "@TecnocreacionesToolsBundle/Resources/config/routing/tabs.yaml"
#    prefix: /tabs

tabs_save_current:
    path: /tabs/save-current.json
    defaults:
        _controller:  TecnocreacionesToolsBundle:Tools:tabSaveCurrent
        _format: json
    requirements: { _method: GET }
    
tabs_object_manager_documents_upload:
    path: /tabs/object-manager/documents/upload
    defaults:
        _controller:  TecnocreacionesToolsBundle:ObjectManager/DocumentManager:upload
        _format: html
    requirements: { _method: POST }
    
tabs_object_manager_documents_delete:
    path: /tabs/object-manager/documents/delete/{filename}
    defaults:
        _controller:  TecnocreacionesToolsBundle:ObjectManager/DocumentManager:delete
        _format: html
    requirements: { _method: GET }
    
tabs_object_manager_documents_get:
    path: /tabs/object-manager/documents/get/{filename}
    defaults:
        _controller:  TecnocreacionesToolsBundle:ObjectManager/DocumentManager:get
        _format: html
    requirements: { _method: GET }
    
tabs_object_exporter_generate:
    path: /tabs/object-manager/exporter/generate
    defaults:
        _controller:  TecnocreacionesToolsBundle:ObjectManager/Exporter:generate
        _format: html
    requirements: { _method: POST }
    options:
        expose: true
    
tabs_object_exporter_get:
    path: /tabs/object-manager/exporter/get/{filename}
    defaults:
        _controller:  TecnocreacionesToolsBundle:ObjectManager/Exporter:get
        _format: html
    requirements: { _method: GET }
    
tabs_object_exporter_delete:
    path: /tabs/object-manager/exporter/delete/{filename}
    defaults:
        _controller:  TecnocreacionesToolsBundle:ObjectManager/Exporter:delete
        _format: html
    requirements: { _method: GET }

tabs_object_exporter_download:
    path: /tabs/object-manager/exporter/download/{filename}
    defaults:
        _controller:  TecnocreacionesToolsBundle:ObjectManager/Exporter:download
        _format: html
    requirements: { _method: GET }
    
tabs_object_note_add:
    path: /tabs/object-manager/note/add
    defaults:
        _controller:  TecnocreacionesToolsBundle:ObjectManager/NoteManager:add
        _format: html
    requirements: { _method: POST }